// TEMPLATE — Must be reviewed and approved by a qualified Indian lawyer
// before going live. Replace all placeholders with real business details.
// This policy references the Digital Personal Data Protection Act, 2023 (DPDP Act).

import PolicyShell, { PolicySection } from "../components/PolicyShell";

const PrivacyPolicy = () => (
  <PolicyShell
    title="Privacy Policy"
    subtitle="We respect your privacy. This policy explains what personal data we collect, why we collect it, and how we protect it."
    lastUpdated="June 2025"
  >
    <PolicySection title="1. Who We Are">
      <p>
        PremSetu is owned and operated by Karmveer Singh (sole proprietor; the
        business is not yet incorporated as a company), based at D-5, Teachers
        Colony, Shradhapuri Phase 2, Meerut, Uttar Pradesh – 250001 (the
        "<strong>Data Fiduciary</strong>" under the Digital Personal Data
        Protection Act, 2023). For questions about this policy, contact us at{" "}
        officialpremsetu@gmail.com.
      </p>
      <p>
        This policy applies to all visitors, registered users, and paying
        members of the PremSetu platform (website and any associated
        applications).
      </p>
    </PolicySection>

    <PolicySection title="2. What Personal Data We Collect">
      <p>
        We collect personal data in two ways: information you provide directly
        and information generated by your use of the Platform.
      </p>
      <p>
        <strong>Information you provide:</strong>
      </p>
      <ul>
        <li>
          <strong>Identity & contact:</strong> Full name, email address, mobile
          phone number, gender, and date of birth.
        </li>
        <li>
          <strong>Profile information:</strong> Religion, caste, gotra, mother
          tongue, city, state, education, profession, annual income, height,
          marital status, and a personal bio.
        </li>
        <li>
          <strong>Additional profile fields:</strong> Dietary preference, family
          type, family values, parents' occupation, number of siblings, manglik
          status, birth time, and birth place.
        </li>
        <li>
          <strong>Photos:</strong> A profile photo and up to several additional
          photos uploaded to your profile.
        </li>
        <li>
          <strong>Payment information:</strong> We do not store card or bank
          details. Payment is made directly via UPI; we retain only the UPI
          transaction reference you provide and your membership status
          (paid / not paid).
        </li>
        <li>
          <strong>Messages:</strong> Text messages sent between users through
          the in-platform chat feature.
        </li>
      </ul>
      <p>
        <strong>Information we collect automatically:</strong>
      </p>
      <ul>
        <li>
          Log data: IP address, browser type, pages visited, timestamps.
        </li>
        <li>
          Usage data: Profiles viewed, interests expressed, searches
          performed.
        </li>
        <li>Cookies and local storage (see Section 9).</li>
      </ul>
    </PolicySection>

    <PolicySection title="3. Sensitive Personal Data">
      <p>
        Under Indian law, certain categories of information are classified as
        sensitive personal data. PremSetu collects the following sensitive
        categories because they are essential to the matrimonial matchmaking
        service you have requested:
      </p>
      <ul>
        <li>
          <strong>Religion & caste</strong> — core matching criteria for most
          Indian families.
        </li>
        <li>
          <strong>Date of birth</strong> — used for age-based matching and
          horoscope features.
        </li>
        <li>
          <strong>Photographs</strong> — profile and gallery photos you choose
          to upload.
        </li>
      </ul>
      <p>
        By submitting this information, you provide explicit consent for us to
        process it for the purposes described in this policy. You can withdraw
        consent by deleting specific fields or closing your account (see
        Section 8).
      </p>
    </PolicySection>

    <PolicySection title="4. How We Use Your Data">
      <p>We use your personal data for the following purposes:</p>
      <ul>
        <li>
          <strong>Matchmaking:</strong> Displaying your profile to other users
          who match your preferences and vice versa, and generating match
          suggestions.
        </li>
        <li>
          <strong>Account management:</strong> Creating and maintaining your
          account, authenticating your login, and processing your membership
          payment.
        </li>
        <li>
          <strong>Communication:</strong> Sending service-related notifications
          (e.g., new interest received, payment receipt). We will not send
          marketing emails without your consent.
        </li>
        <li>
          <strong>Safety & fraud prevention:</strong> Detecting and preventing
          fake profiles, fraud, and misuse of the Platform.
        </li>
        <li>
          <strong>Legal compliance:</strong> Meeting our obligations under
          applicable Indian laws, including responding to lawful requests from
          courts or government authorities.
        </li>
        <li>
          <strong>Platform improvement:</strong> Aggregated, anonymised usage
          analytics to improve features.
        </li>
      </ul>
    </PolicySection>

    <PolicySection title="5. Who We Share Your Data With">
      <p>
        We do not sell your personal data. We share it only in the following
        circumstances:
      </p>
      <ul>
        <li>
          <strong>Other users:</strong> Your profile is visible to other
          registered users. Paid members see your full profile; unpaid users
          and logged-out visitors see only public fields (name, age, city,
          state, gender, and profile photo).
        </li>
        <li>
          <strong>Cloudinary:</strong> Your photos are stored on Cloudinary's
          servers. Cloudinary acts as a data processor on our behalf and is
          bound by applicable data protection standards.
        </li>
        <li>
          <strong>UPI apps:</strong> Payments are made through your own UPI
          app (PhonePe, Google Pay, Paytm, etc.), which processes your payment
          details under its own privacy policy. We encourage you to review
          your UPI app's privacy policy before completing a payment.
        </li>
        <li>
          <strong>Legal authorities:</strong> If required by law, court order,
          or to protect the rights or safety of users.
        </li>
      </ul>
    </PolicySection>

    <PolicySection title="6. Data Security">
      <p>
        We implement appropriate technical and organisational measures to
        protect your personal data against unauthorised access, disclosure,
        alteration, or destruction. These include:
      </p>
      <ul>
        <li>HTTPS encryption for all data in transit.</li>
        <li>
          Passwords stored as hashed values (never in plain text) using
          industry-standard hashing algorithms.
        </li>
        <li>JWT-based authentication with server-side token validation.</li>
        <li>
          Database access restricted to application servers; no public
          exposure of database credentials.
        </li>
        <li>
          Photos stored on Cloudinary with access controlled via signed URLs
          where applicable.
        </li>
      </ul>
      <p>
        No system is completely secure. While we take reasonable steps to
        protect your data, we cannot guarantee absolute security. Please use
        a strong, unique password for your PremSetu account.
      </p>
    </PolicySection>

    <PolicySection title="7. Data Retention">
      <p>
        We retain your personal data for as long as your account is active
        or as necessary to provide the service and comply with legal
        obligations.
      </p>
      <ul>
        <li>
          <strong>Active accounts:</strong> Data is retained for the lifetime
          of the account.
        </li>
        <li>
          <strong>Deleted accounts:</strong> We will delete or anonymise your
          personal data within 90 days of account deletion,
          except where retention is required by law (e.g., financial records
          for 7 years under Indian accounting rules).
        </li>
        <li>
          <strong>Messages:</strong> Chat messages may be retained for a
          limited period after account deletion for fraud prevention purposes.
        </li>
      </ul>
    </PolicySection>

    <PolicySection title="8. Your Rights (DPDP Act, 2023)">
      <p>
        Under the Digital Personal Data Protection Act, 2023, and applicable
        Indian law, you have the following rights as a Data Principal:
      </p>
      <ul>
        <li>
          <strong>Right to access:</strong> Request a summary of the personal
          data we hold about you and how it is being processed.
        </li>
        <li>
          <strong>Right to correction:</strong> Request correction of
          inaccurate or incomplete personal data. You can update most profile
          fields directly from the Edit Profile page.
        </li>
        <li>
          <strong>Right to erasure:</strong> Request deletion of your personal
          data. You can delete your account by contacting us at{" "}
          officialpremsetu@gmail.com. Note that some data may be retained
          for legal compliance (see Section 7).
        </li>
        <li>
          <strong>Right to withdraw consent:</strong> You may withdraw consent
          for processing sensitive personal data at any time. Withdrawal may
          affect your ability to use the Platform.
        </li>
        <li>
          <strong>Right to grievance redressal:</strong> You may lodge a
          complaint with our Grievance Officer (see Section 11) or with the
          Data Protection Board of India once established.
        </li>
      </ul>
      <p>
        To exercise any of these rights, contact us at{" "}
        officialpremsetu@gmail.com. We will respond within{" "}
        30 days.
      </p>
    </PolicySection>

    <PolicySection title="9. Cookies & Local Storage">
      <p>
        PremSetu uses browser <strong>localStorage</strong> to store your
        authentication token so that you remain logged in across sessions. We
        do not use third-party advertising cookies.
      </p>
      <p>
        You can clear localStorage at any time through your browser settings,
        which will log you out of the Platform.
      </p>
    </PolicySection>

    <PolicySection title="10. Children's Privacy">
      <p>
        PremSetu is strictly for users aged 18 and above. We do not
        knowingly collect personal data from anyone under 18. If we become
        aware that a user is under 18, we will delete their account and data
        promptly.
      </p>
    </PolicySection>

    <PolicySection title="11. Grievance Officer">
      <p>
        In accordance with the Information Technology (Intermediary Guidelines
        and Digital Media Ethics Code) Rules, 2021, the name and contact of
        the Grievance Officer is:
      </p>
      <p>
        <strong>Name:</strong> Karmveer Singh
        <br />
        <strong>Designation:</strong> Grievance Officer
        <br />
        <strong>Email:</strong> officialpremsetu@gmail.com
        <br />
        <strong>Phone:</strong> +91 74098 68966
        <br />
        <strong>Address:</strong> D-5, Teachers Colony, Shradhapuri Phase 2, Meerut, Uttar Pradesh – 250001
      </p>
      <p>
        The Grievance Officer will acknowledge your complaint within{" "}
        <strong>24 hours</strong> and resolve it within{" "}
        <strong>30 days</strong>.
      </p>
    </PolicySection>

    <PolicySection title="12. Changes to This Policy">
      <p>
        We may update this Privacy Policy from time to time to reflect
        changes in our practices or applicable law. The updated policy will
        be posted on this page with a revised "Last updated" date. We will
        notify registered users of material changes by email or an in-app
        notice.
      </p>
    </PolicySection>

    <PolicySection title="13. Contact">
      <p>
        For any privacy-related queries, please contact:
      </p>
      <p>
        <strong>Karmveer Singh (Proprietor, PremSetu)</strong>
        <br />
        D-5, Teachers Colony, Shradhapuri Phase 2, Meerut, Uttar Pradesh – 250001
        <br />
        Email: officialpremsetu@gmail.com
        <br />
        Phone: +91 74098 68966
      </p>
    </PolicySection>
  </PolicyShell>
);

export default PrivacyPolicy;
